#!/usr/bin/env python3
"""Import existing books into D1 books + book_chapters tables."""
import os
import re
from pathlib import Path
from bs4 import BeautifulSoup

BOOKS = [
    {"dir": "oikos_church/zh/book2", "title": "家教会的本体论革命", "language": "zh"},
    {"dir": "oikos_church/en/book2", "title": "The Ontological Revolution of the House Church", "language": "en"},
]

def extract_chapters(book_dir):
    """Extract chapter list from index.html."""
    index_path = Path(book_dir) / "index.html"
    if not index_path.exists():
        return []
    soup = BeautifulSoup(index_path.read_text(encoding="utf-8"), "html.parser")
    chapters = []
    for i, link in enumerate(soup.select("a[href]"), 1):
        href = link.get("href", "")
        title = link.get_text(strip=True)
        if href.endswith(".html") and title:
            chapters.append({
                "chapter_number": i,
                "title": title.replace("'", "''"),
                "content_path": f"{book_dir}/{href}",
                "sort_order": i,
            })
    return chapters

def generate_sql():
    lines = ["-- Auto-generated by scripts/import-books.py"]
    for book in BOOKS:
        if not Path(book["dir"]).exists():
            continue
        book_id = f"book-{book['language']}-001"
        title = book["title"].replace("'", "''")
        lines.append(
            f"INSERT OR IGNORE INTO books (id, title, language, source_path, status) "
            f"VALUES ('{book_id}', '{title}', '{book['language']}', '{book['dir']}', 'published');"
        )
        chapters = extract_chapters(book["dir"])
        for ch in chapters:
            ch_id = f"{book_id}-ch{ch['chapter_number']:03d}"
            lines.append(
                f"INSERT OR IGNORE INTO book_chapters (id, book_id, chapter_number, title, content_path, sort_order) "
                f"VALUES ('{ch_id}', '{book_id}', {ch['chapter_number']}, '{ch['title']}', '{ch['content_path']}', {ch['sort_order']});"
            )
    return "\n".join(lines)

if __name__ == "__main__":
    print(generate_sql())
